# Generated by Django 4.0.1 on 2022-01-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cooperativa', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('ciudad_matriz', models.CharField(max_length=255)),
                ('direccion_matriz', models.CharField(max_length=255)),
            ],
        ),
    ]
