# Generated by Django 4.0.1 on 2022-01-27 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientos', '0001_initial'),
        ('ordenes_compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos.asiento')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes_compra.orden_compra')),
            ],
            options={
                'unique_together': {('orden_compra', 'asiento')},
            },
        ),
    ]
