# Generated by Django 4.1 on 2022-08-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='hora',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
